export const CLEAR_MOVIE_LATEST_LIST='CLEAR_MOVIE_LATEST_LIST' 
export const SET_MOVIE_LATEST_LIST='SET_MOVIE_LATEST_LIST'

export const CLEAR_MOVIE_NOW_PLAYING_LIST='CLEAR_MOVIE_NOW_PLAYING_LIST' 
export const SET_MOVIE_NOW_PLAYING_LIST='SET_MOVIE_NOW_PLAYING_LIST'

export const CLEAR_MOVIE_POPULAR_LIST='CLEAR_MOVIE_POPULAR_LIST' 
export const SET_MOVIE_POPULAR_LIST='SET_MOVIE_POPULAR_LIST'

export const CLEAR_MOVIE_TOP_RATED_LIST='CLEAR_MOVIE_TOP_RATED_LIST' 
export const SET_MOVIE_TOP_RATED_LIST='SET_MOVIE_TOP_RATED_LIST'

export const CLEAR_MOVIE_UPCOMING_LIST='CLEAR_MOVIE_UPCOMING_LIST' 
export const SET_MOVIE_UPCOMING_LIST='SET_MOVIE_UPCOMING_LIST'

export const CLEAR_MOVIE_DETAIL='CLEAR_MOVIE_DETAIL' 
export const SET_MOVIE_DETAIL='SET_MOVIE_DETAIL'